board/urls.py
from django.urls import path
from .views import base_views, board_views, reply_views

app_name = 'board'
urlpatterns = [
    # base_views
    path('',base_views.index,name='index'),
    path('<int:board_id>/',base_views.detail,name='detail'),

    # board_views
    path('board/create/',board_views.board_create,name='board_create'),
    path('board/modify/<int:board_id>/',board_views.board_modify,name='board_modify'),
    path('board/delete/<int:board_id>/',board_views.board_delete,name='board_delete'),
    path('board/vote/<int:board_id>/',board_views.board_vote,name='board_vote'),

    # reply_views
    path('reply/create/<int:board_id>/',reply_views.reply_create,name='reply_create'),
    path('reply/modify/<int:reply_id>/',reply_views.reply_modify,name='reply_modify'),
    path('reply/delete/<int:reply_id>/',reply_views.reply_delete,name='reply_delete'),
    path('reply/vote/<int:reply_id>/',reply_views.reply_vote,name='reply_vote'),

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='common/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.signup,name='signup'),
    path('whole_map/', views.all_mark,name='whole_map'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('search/', views.search, name="search"),
]

board/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Board

def index(request):
    page = request.GET.get('page','1') # 페이지
    kw = request.GET.get('kw','') # 검색어
    board_list = Board.objects.order_by('-create_date')
    if kw:
        board_list = board_list.filter(
            Q(subject__icontains=kw) | # 제목 검색
            Q(content__icontains=kw) | # 내용 검색
            Q(reply__content__icontains=kw) | # 댓글 내용 검색
            Q(author__username__icontains=kw) | # 게시판 글쓴이 검색
            Q(reply__author__username__icontains=kw)  # 댓글 글쓴이 검색
        ).distinct()
    paginator = Paginator(board_list, 10) # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'board_list':page_obj, 'page':page, 'kw':kw}
    return render(request,'board/board_list.html', context)

def detail(request,board_id):
    board = get_object_or_404(Board, pk=board_id)
    context = {'board':board,}
    return render(request,'board/board_detail.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <!-- CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <title>3조</title>
    </head>

    <body>
        <!-- 네비게이션바 -->
        {% include 'navbar.html' %}


        <!-- 기본 템플릿 안에 삽입될 내용 Start -->
        {% block content %}
        {% endblock %}
        <!-- 기본 템플릿 안에 삽입될 내용 End -->

        <!-- Bootstrap JS -->
        <script src="{% static 'js/bootstrap.min.js' %}"></script>

        <!-- Jquery -->
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        
        <!-- map.js -->
        <script src="{% static 'js/map.js' %}"></script>

        <!-- KKO_Map -->
        <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=d11f13b943aa92d09a14a655880f62bf&libraries=services,clusterer,drawing"></script>

        <!-- 자바스크립트 Start -->
        {% block script %}
        {% endblock %}
        <!-- 자바스크립트 End -->

    </body>

</html>

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">등山하三</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li>
                    <a class="nav-link" href="{% url 'board:index' %}">게시판</a>
                </li>
                <li>
                    <a class="nav-link" href="{% url 'common:whole_map' %}">전체지도</a>
                </li>
            </ul>
        </div>
    </div>
</nav>