board/urls.py
from django.urls import path
from .views import base_views, board_views, reply_views

app_name = 'board'
urlpatterns = [
    # base_views
    path('',base_views.index,name='index'),
    path('<int:board_id>/',base_views.detail,name='detail'),

    # board_views
    path('board/create/',board_views.board_create,name='board_create'),
    path('board/modify/<int:board_id>/',board_views.board_modify,name='board_modify'),
    path('board/delete/<int:board_id>/',board_views.board_delete,name='board_delete'),
    path('board/vote/<int:board_id>/',board_views.board_vote,name='board_vote'),

    # reply_views
    path('reply/create/<int:board_id>/',reply_views.reply_create,name='reply_create'),
    path('reply/modify/<int:reply_id>/',reply_views.reply_modify,name='reply_modify'),
    path('reply/delete/<int:reply_id>/',reply_views.reply_delete,name='reply_delete'),
    path('reply/vote/<int:reply_id>/',reply_views.reply_vote,name='reply_vote'),

]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('search/', views.search, name="search"),
]

board/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Board(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_board')
    subject = models.CharField(max_length=250)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_board') # 추천인 추가

    def __str__(self) -> str:
        return self.subject

class Reply(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_reply')
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_reply')

board/forms.py
from django import forms
from .models import Board, Reply

class BoardForm(forms.ModelForm):

    class Meta:
        model = Board # 사용할 모델
        fields = ['subject','content'] # BoardForm에서 사용할 Board 모델의 속성

        labels = {
            'subject':'제목',
            'content':'내용',
        }

class ReplyForm(forms.ModelForm):

    class Meta:
        model = Reply
        fields = ['content']

        labels = {
            'content':'답글내용'
        }

board/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Board

def index(request):
    page = request.GET.get('page','1') # 페이지
    kw = request.GET.get('kw','') # 검색어
    board_list = Board.objects.order_by('-create_date')
    if kw:
        board_list = board_list.filter(
            Q(subject__icontains=kw) | # 제목 검색
            Q(content__icontains=kw) | # 내용 검색
            Q(reply__content__icontains=kw) | # 댓글 내용 검색
            Q(author__username__icontains=kw) | # 게시판 글쓴이 검색
            Q(reply__author__username__icontains=kw)  # 댓글 글쓴이 검색
        ).distinct()
    paginator = Paginator(board_list, 10) # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'board_list':page_obj, 'page':page, 'kw':kw}
    return render(request,'board/board_list.html', context)

def detail(request,board_id):
    board = get_object_or_404(Board, pk=board_id)
    context = {'board':board,}
    return render(request,'board/board_detail.html', context)

board/views/board_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..models import Board
from ..forms import BoardForm

@login_required(login_url='common:login')
def board_create(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.author = request.user # author 속성에 로그인 계정 저장
            board.create_date = timezone.now()
            board.save()
            return redirect('board:index')
    else:
        form = BoardForm()
    context = {'form':form}
    return render(request,'board/board_form.html',{'form':form})

@login_required(login_url='common:login')
def board_modify(request,board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages.error(request, '수정권한이 없습니다!')
        return redirect('board:detail',board_id=board.id)
    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            board.modify_date = timezone.now() # 수정일시 저장
            board.save()
            return redirect('board:detail',board_id=board.id)
    else:
        form = BoardForm(instance=board)
    context = {'form':form}
    return render(request, 'board/board_form.html', context)

@login_required(login_url='common:login')
def board_delete(request,board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user != board.author:
        messages(request, '삭제권한이 없습니다!')
        return redirect('board:detail', board_id=board.id)
    board.delete()
    return redirect('board:index')

@login_required(login_url='common:login')
def board_vote(request,board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.user == board.author:
        messages.error(request, '본인이 작성한 글은 추천할수 없습니다!')
    else:
        board.voter.add(request.user)
    return redirect('board:detail',board_id=board.id) 

board/views/reply_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone

from ..models import Board, Reply
from ..forms import ReplyForm

@login_required(login_url='common:login')
def reply_create(request,board_id):
    board = get_object_or_404(Board, pk=board_id)
    if request.method == "POST":
            form = ReplyForm(request.POST)
            if form.is_valid():
                reply = form.save(commit=False)
                reply.author = request.user # author 속성에 로그인 계정 저장
                reply.create_date = timezone.now()
                reply.board = board
                reply.save()
                return redirect('{}#reply_{}'.format(resolve_url('board:detail', board_id=board.id), reply.id))
                    
    else:
        form = ReplyForm()
    context = {'board': board, 'form': form}
    return render(request, 'board/board_detail.html', context)

@login_required(login_url='common:login')
def reply_modify(request,reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.author:
        messages(request, '수정권한이 없습니다!')
        return redirect('board:detail', board_id=reply.board.id)
    if request.method == "POST":
        form = ReplyForm(request.POST, instance=reply)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.modify_date = timezone.now()
            reply.save()
            return redirect('{}#reply_{}'.format(resolve_url('board:detail', board_id=reply.board.id), reply.id))
    else:
        form = ReplyForm(instance=reply)
    context = {'reply':reply, 'form':form}
    return render(request, 'board/board_form.html', context)

@login_required(login_url='common:login')
def reply_delete(request,reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user != reply.author:
        messages(request, '삭제권한이 없습니다!')
        return redirect('board:detail', board_id=reply.board.id)
    else:
        reply.delete()
    return redirect('board:detail', board_id=reply.board.id)

@login_required(login_url='common:login')
def reply_vote(request,reply_id):
    reply = get_object_or_404(Reply, pk=reply_id)
    if request.user == reply.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다!')
    else:
        reply.voter.add(request.user)
    return redirect('{}#reply_{}'.format(resolve_url('board:detail', board_id=reply.board.id), reply.id))

templates/board/board_detail.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}

<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}

    <!-- 게시판 -->
    <h2 class="border-bottom py-2">{{ board.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ board.content|mark }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ board.author.username }}</div>
                    <div>
                        {% if board.modify_date == null %}
                        {{ board.create_date }}
                        {% else %}
                        {{ board.modify_date }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="my-3">
                <a href="#"
                   data-uri="{% url 'board:board_vote' board.id %}"
                   class="recommend btn btn-sm btn-outline-secondary">추천
                    <span class="badge rounded-pill bg-success">{{ board.voter.count }}</span>
                </a>
                {% if request.user == board.author %}
                <a href="{% url 'board:board_modify' board.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#"
                   class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'board:board_delete' board.id %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>

    <!-- 댓글 -->
    <h5 class="border-bottom my-3 py-2">{{board.reply_set.count}}개의 답변이 있습니다.</h5>
    {% for reply in board.reply_set.all %}
    <a id="reply_{{ reply.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text">{{ reply.content|mark }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2 text-start">
                    <div class="mb-2">{{ reply.author.username }}</div>
                    <div>
                        {% if reply.modify_date == null %}
                        {{ reply.create_date }}
                        {% else %}
                        {{ reply.modify_date }}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="my-3">
                <a href="#"
                data-uri="{% url 'board:reply_vote' reply.id %}"
                class="recommend btn btn-sm btn-outline-secondary">추천
                 <span class="badge rounded-pill bg-success">{{ reply.voter.count }}</span>
                </a>
                {% if request.user == reply.author %}
                <a href="{% url 'board:reply_modify' reply.id %}"
                   class="btn btn-sm btn-outline-secondary">수정</a>
                <a href="#"
                   class="delete btn btn-sm btn-outline-secondary"
                   data-uri="{% url 'board:reply_delete' reply.id %}">삭제</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}

    <!-- 댓글 등록 -->
    <form action="{% url 'board:reply_create' board.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">댓글내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

{% block script %}

<script type='text/javascript'>
    
    const delete_elements = document.getElementsByClassName("delete");
    Array.from(delete_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 삭제하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });

    const recommend_elements = document.getElementsByClassName("recommend");
    Array.from(recommend_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            if(confirm("정말로 추천하시겠습니까?")) {
                location.href = this.dataset.uri;
            };
        });
    });
    
</script>

{% endblock %}

templates/board/board_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시판 등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>

{% endblock %}

templates/board/board_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}

<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'board:board_create' %}" class="btn btn-primary">게시판 등록</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr class="text-center table-dark">
                <th>번호</th>
                <th style="width: 50%;">제목</th>
                <th>작성자</th>
                <th>작성일시</th>
            </tr>
        </thead>
        <tbody>
        {% if board_list %}
        {% for board in board_list %}
        <tr>
            <td align="center">
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td class="text-center">
                <a href="{% url 'board:detail' board.id %}">{{ board.subject }}</a>
                {% if board.reply_set.count > 0 %}
                <span class="text-danger small mx-2">{{board.reply_set.count}}</span>
                {% endif %}
            </td>
            <td align="center">{{ board.author.username }}</td> <!-- 글쓴이 추가 -->
            <td align="center">{{ board.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="4">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>

    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if board_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in board_list.paginator.page_range %}
        {% if page_number >= board_list.number|add:-5 and page_number <= board_list.number|add:5 %}
        {% if page_number == board_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ board_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
<form id="searchForm" method="get" action="{% url 'board:index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>

{% endblock %}

{% block script %}

<script type='text/javascript'>

    const page_elements = document.getElementsByClassName("page-link");
    Array.from(page_elements).forEach(function(element) {
        element.addEventListener('click', function() {
            document.getElementById('page').value = this.dataset.page;
            document.getElementById('searchForm').submit();
        });
    });
    
    const btn_search = document.getElementById("btn_search");
    btn_search.addEventListener('click', function() {
        document.getElementById('kw').value = document.getElementById('search_kw').value;
        document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        document.getElementById('searchForm').submit();
    });

</script>

{% endblock %}